# Generated by Django 3.0.2 on 2020-06-10 23:35

import LMS_DB.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist_Registar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unique_Id_Generation', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Artists_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artist_Unique_Id', models.CharField(max_length=10)),
                ('Artist_Name', models.CharField(max_length=100)),
                ('Artist_location', models.CharField(max_length=10)),
                ('Artist_Birthday', models.CharField(max_length=10)),
                ('Artist_Done_Events', models.CharField(max_length=1000)),
                ('Artist_Registration_Date_time', models.CharField(max_length=100)),
                ('Artist_Authentication', models.CharField(max_length=100)),
                ('Artist_points', models.IntegerField(max_length=10)),
                ('Artist_authenticated', models.CharField(max_length=10)),
                ('Artist_type', models.CharField(max_length=100)),
                ('Artist_field', models.CharField(max_length=100)),
                ('Artist_ratings', models.IntegerField(max_length=10)),
                ('age', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='End_user_registar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unique_Id_Generation', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Registar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organiser_name', models.CharField(max_length=10)),
                ('event_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('artists', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('event_poster', models.FileField(upload_to='')),
                ('capacity', models.CharField(max_length=100)),
                ('date', models.DateField(max_length=20)),
                ('time', models.TimeField(max_length=20)),
                ('authentication', models.CharField(default='NO', max_length=10)),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_Unique_Id', models.CharField(default=LMS_DB.models.unique_rand, max_length=8, unique=True)),
                ('Event_By', models.CharField(max_length=100)),
                ('Event_Name', models.CharField(max_length=500)),
                ('Event_Type', models.CharField(max_length=20)),
                ('Event_Organiser', models.CharField(max_length=50)),
                ('Organiser_Unique_Id', models.IntegerField(default=0, max_length=10)),
                ('Artist_Name', models.CharField(max_length=50)),
                ('Artists_Unique_Id', models.IntegerField(default=0, max_length=10)),
                ('Event_Venue', models.CharField(max_length=50)),
                ('Venue_Unique_id', models.CharField(max_length=100)),
                ('Event_Authentication', models.CharField(default=False, max_length=10)),
                ('Event_Status', models.CharField(default='Inactive', max_length=10)),
                ('Event_Description', models.TextField(max_length=1000)),
                ('Event_Poster', models.ImageField(upload_to='')),
                ('Event_Date', models.CharField(default=datetime.date.today, max_length=100)),
                ('Event_Time', models.TimeField(default=0, max_length=20)),
                ('Event_Registration_Time', models.DateTimeField(auto_now_add=True)),
                ('Event_Price', models.IntegerField(max_length=6)),
                ('Event_Capacity', models.IntegerField(max_length=6)),
                ('Event_Tickets_Sold', models.IntegerField(default=0, max_length=6)),
                ('Event_Seats_Sold', models.CharField(default='', max_length=1000)),
                ('Rows', models.IntegerField(default=12, max_length=2)),
                ('Columns', models.IntegerField(default=12, max_length=2)),
                ('Blocked_Seats', models.CharField(default=0, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Organiser_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organiser_Unique_id', models.CharField(max_length=10)),
                ('Organiser_Points', models.CharField(max_length=2)),
                ('Organiser_Name', models.CharField(max_length=100)),
                ('Organised_Events_id', models.CharField(max_length=100)),
                ('Organiser_Connected_with_Artists', models.CharField(max_length=100)),
                ('Organiser_Authenication', models.CharField(max_length=10)),
                ('Organiser_Rating', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Organiser_Registar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unique_Id_Generation', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_Name', models.CharField(max_length=100)),
                ('Event_Unique_Id', models.IntegerField(max_length=10)),
                ('User_Name', models.CharField(max_length=100)),
                ('User_Unique_id', models.IntegerField(max_length=10)),
                ('Organiser_Unique_Id', models.IntegerField(max_length=10)),
                ('Number_of_tickets', models.IntegerField(max_length=10)),
                ('Seat_no', models.CharField(max_length=100)),
                ('Payment_Method', models.CharField(max_length=10)),
                ('Payment_Reciept_Path', models.CharField(max_length=10)),
                ('Payment_Status', models.CharField(max_length=10)),
                ('Offers_Applied', models.CharField(max_length=10)),
                ('Payment_Amount', models.IntegerField()),
                ('Ticket_Registration_Time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users_Master',
            fields=[
                ('Users_unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=10)),
                ('Surname', models.CharField(max_length=10)),
                ('Country', models.CharField(max_length=10)),
                ('State', models.CharField(max_length=10)),
                ('City', models.CharField(max_length=10)),
                ('User_Log', models.DateTimeField(auto_now_add=True)),
                ('User_last_Login', models.CharField(max_length=10)),
                ('User_authentication', models.CharField(max_length=10)),
                ('User_tickets', models.CharField(max_length=1000)),
                ('liked_events', models.CharField(max_length=10)),
                ('Contact_Number', models.CharField(default=0, max_length=15)),
                ('Email', models.CharField(default='-', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Venue_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Venue_Unique_Id', models.CharField(max_length=20)),
                ('Venue_name', models.CharField(max_length=20)),
                ('Venue_Layout_Path', models.CharField(max_length=200)),
                ('Venue_Seats', models.IntegerField(max_length=8)),
                ('Venue_Facilities', models.CharField(max_length=500)),
                ('Events_hosted', models.IntegerField(max_length=6)),
                ('Venue_Rating', models.IntegerField(max_length=10)),
                ('Venue_address', models.CharField(max_length=100)),
                ('Venue_City', models.CharField(max_length=20)),
                ('Venue_State', models.CharField(max_length=100)),
                ('Venue_Status', models.CharField(max_length=100)),
                ('Venue_Pics_Paths', models.CharField(max_length=110)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(default='1000', editable=False, max_length=200)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='LMS_DB.Users_Master')),
            ],
        ),
    ]
