# Generated by Django 3.0.2 on 2020-06-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_DB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_master',
            name='User_last_Login',
            field=models.CharField(max_length=100),
        ),
    ]
