# Generated by Django 3.0.2 on 2020-06-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_DB', '0002_auto_20200610_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_master',
            name='City',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='users_master',
            name='Country',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='users_master',
            name='Name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='users_master',
            name='State',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='users_master',
            name='Surname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='users_master',
            name='liked_events',
            field=models.CharField(max_length=30),
        ),
    ]
